server:
  port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/client?currentSchema=test"
    username: "client"
    password: "123"

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        default_schema: "test"
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  flyway:
    enabled: true
    locations: "classpath:db/migration"
    url: "jdbc:postgresql://localhost:5432/client"
    password: "123"
    username: "client"
    schemas: "test"
